### PR TITLE
back end was manually merged

### PR DESCRIPTION
**Pull request by 8000meters**
We integrated the backend functionality. all the route handlers are running for the event related functions. successful communication with the MongoDB. GET, PATCH, POST, DELETE are all operational for Events.

### CODE REVIEW

**Comment by 8000meters** [comment]
ok looks good

**Review by rich9029 — APPROVED** [review]
1. React downgraded from 18 to 17 to account for older code base
2. Changes made in reducers: actionTypes.js and action.js moved into actions subfolder
3. Changed render to match React v17 client/index.js

**Review by rich9029 — APPROVED** [review]
This was previously approved - backlog in commits.

**Review by rich9029 — APPROVED** [review]
Last working version.

**Review by rich9029 — APPROVED** [review]
Last working version - need to make sure we make smaller commits and everyone has individual working branches.

**Pull request merged**
